mutation insertOneAccount(
  $accountName: String!
  $accountNumber: String!
  $bankName: String!
  $bankCode: String!
  $createdAt: DateTime!
  $updatedAt: DateTime!
) {
  insertOneAccount(
    data: {
      accountName: $accountName
      accountNumber: $accountNumber
      bankName: $bankName
      bankCode: $bankCode
      createdAt: $createdAt
      updatedAt: $updatedAt
    }
  ) {
    _id
  }
}
