query fetchMyEvents($email: String!, $lastId: String) {
  MyPaginatedEvents(input: { lastId: $lastId, email: $email }) {
    moddedListedEvents
    count
    events {
      _id
      eventTitle
      eventDescription
      isProvisions
      eventDate
      eventImage
      color
      textColor
      soldOut
      organiser
      agents {
        email
      }
      # thirdParties {
      #   email
      # }
    }
  }
}
