query fetchEvents(
  $eventsRoute: Boolean!
  $lastId: String
  $category: String
  $timeline: PaginatedEventsInputQueryTimeline
  $price: PaginatedEventsInputQueryPrice
) {
  PaginatedEvents(
    input: {
      lastId: $lastId
      query: { category: $category, timeline: $timeline, price: $price }
    }
  ) {
    count
    events {
      _id
      eventTitle
      eventDescription @include(if: $eventsRoute)
      cheapestTicket {
        ticketPrice
      }
      isProvisions
      eventDate
      eventImage
      color
      textColor
      soldOut
    }
  }
}
