query fetchMyEvents($email: String!) {
  events(
    sortBy: CREATEDAT_DESC
    query: {
      OR: [
        { organiser: { email: $email } }
        { agents_in: { email: $email } }
        { thirdParties_in: { email: $email } }
      ]
    }
  ) {
    _id
    eventTitle
    eventDescription
    isProvisions
    eventDate
    eventImage
    color
    textColor
    soldOut
    organiser {
      email
    }
    agents {
      email
    }
    thirdParties {
      email
    }
  }
}
