query fetchEvents($eventsRoute: Boolean!, $lastId: String) {
  PaginatedEvents(input: $lastId) {
    count
    events {
      _id
      eventTitle
      eventDescription @include(if: $eventsRoute)
      cheapestTicket {
        ticketPrice
      }
      isProvisions
      eventDate
      eventImage
      color
      textColor
      soldOut
    }
  }
}
